### ISSUE TITLE
Fix tests failing on circle

### ISSUE THREAD

**Issue by ghost** [coatue-oss/ngcomponent#4]
So tests that fail are using the DOM with [renderComponent](https://github.com/coatue/ngcomponent/blob/9510c12ebe9ef758459b0f23841a7b3465afb752/test.ts#L243-L267).

Since the other tests pass, presumably karma is able to start with a browser, so unsure as to why tests are failing.  Any ideas?

![image](https://cloud.githubusercontent.com/assets/681288/23973032/828114dc-0991-11e7-9a11-9ca3bb883982.png)

**Comment by bcherny** [comment]
Since we probably want to avoid a hard dependency on ngimport, try injecting `$compile` instead of using `ngimport`'s version. Eg. see https://github.com/coatue/react2angular/blob/ecd046d40ef49777233446a6944e2b5832551824/test.tsx#L45

**Comment by ghost** [comment]
finally a passing build - https://circleci.com/gh/coatue/ngcomponent/22

**Comment by ghost** [comment]
Fixed
